### ISSUE TITLE
获取时长问题

### ISSUE THREAD

**Issue by zhenggezuishuai** [zhangliangming/HPAudio#1]
你好 我按照您这个demo设计做出来了 但是后台因为各种音频格式的计算时长特别麻烦所以把时长计算放在了android 但是我现在获取时长确特别慢 不能像android一样瞬间获取 请问您有什么好的办法吗

**Comment by zhangliangming** [comment]
@zhenggezuishuai 我这个只要是在android项目里面使用的。
你可以参考这个java版本的：https://github.com/tulskiy/musique 的。
建议：
1.先确定是什么音频格式在获取时长的时候特别慢
2.再确定具体是哪一行代码比较耗时

**Comment by zhenggezuishuai** [comment]
> @zhenggezuishuai 我这个只要是在android项目里面使用的。
> 你可以参考这个java版本的：https://github.com/tulskiy/musique 的。
> 建议：
> 1.先确定是什么音频格式在获取时长的时候特别慢
> 2.再确定具体是哪一行代码比较耗时

我问的就是安卓  我做这个的时候因为java后台获取时间的属性确实太多了不能做到一一适配  所以需要进行前端处理 前端处理的时间现在是1.5秒 稍微有点长了 所以想问问你有什么好的解决办法  我看你这个demo只有一种后台获取音频时长  没有做直接根据url获取

**Comment by zhangliangming** [comment]
@zhenggezuishuai 我发你的那个java项目地址，它是可以适配多种音频格式的。目前这个项目只支持几种音频格式，只支持本地文件获取时长。如果你要根据url获取，这个要确保所有的属性信息都下载到本地的一个音频文件。

**Comment by zhangliangming** [comment]
@zhenggezuishuai 我之前在用那个java项目的时候，感觉还好吧，好多音频格式解析都是毫秒的。

**Comment by zhenggezuishuai** [comment]
> @zhenggezuishuai我之前在用那个java项目的时候，感觉还好吧，好多音频格式解析都是几分钟的。

那你那边是怎么用java获取flac格式的音频文件的时长的 我这边试了好多种方法都做不到这一步

**Comment by zhangliangming** [comment]
@zhenggezuishuai 我之前就是参考那个java版本的项目来修改成一个android的项目。不过在android项目上面，解析flac格式的音频时长相对耗时比较长，它原java项目就比较快。它是基于一个开源的jmac-1.74.jar的基础上开发的。http://jmac.sourceforge.net/

**Comment by zhenggezuishuai** [comment]
> @zhenggezuishuai我之前就是参考那个java版本的项目来修改成一个android的项目。不过在android项目上面，解析flac格式的音频时长相对耗时比较长，它原java项目就比较比较快。它是基于一个开源的JMAC-1.74.jar的基础上开发的。http://jmac.sourceforge.net/

好的 谢谢了
